### PR TITLE
Fixing path configuration for onDemand BTR

### LINKED ISSUE #275: On-demand BTR does not respect the per path configuration in the dojorc
**Bug**

On-demand BTR uses the global `static` configuration regardless of the specific path configuration set in the dojorc. On-demand BTR should use the configuration from the dojorc for paths when they are defined.

### PR DESCRIPTION
**Pull request by rorticus**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**

"on-demand" BTR does the initial build fine, but subsequent watched builds don't honor the path configuration you might have set up in your `.dojorc`. This has been fixed by taking the path name and matching it (if possible) against your path configuration.

Resolves #275

### CODE REVIEW

**Review by matt-gadd — APPROVED** [review]

File: src/build-time-render/BuildTimeRender.ts [hunk 1]
```diff
@@ -69,6 +69,14 @@ function genHash(content: string): string {
...
+function normalizePath(path: string) {
+	return path
+		.replace(/#.*/, '')
+		.replace(/\/$/, '')
+		.replace(/^\//, '')
+		.toLowerCase();
+}
+
 const trailingSlash = new RegExp(/\/$/);
 const leadingSlash = new RegExp(/^\//);
```
Comment (agubler) [inline src/build-time-render/BuildTimeRender.ts:81]: These were the regexs I thought could be re-used - or maybe replaced by the normalizePath else where

**Review by agubler — APPROVED** [review]

File: src/build-time-render/BuildTimeRender.ts (hunk 1 above)
Comment (rorticus) [reply src/build-time-render/BuildTimeRender.ts:81]: Ah! Good catch. Let me see if I can use normalizePath in other places and clean this up some 👍
